name: Algo CI & Quality Check

on:
  push:
    branches: [ dev ]
  pull_request:

  workflow_dispatch:

jobs:
  build-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java files
        run: |
          find Algorithm -name "*.java" > sources.txt
          javac @sources.txt

      - name: Run PMD (Code Quality)
        run: |
          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases/6.55.0/pmd-bin-6.55.0.zip
          unzip -q pmd.zip
          pmd-bin-6.55.0/bin/run.sh pmd \
            -d Algorithm \
            -R rulesets/java/quickstart.xml \
            -f text || true


      - name: Run Algo Analyzer
        run: |
          python3 analysis/analyze_algo.py

      - name: Commit updated metrics
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add metrics/metrics.json || true
          git commit -m "Update algo metrics [CI]" || true
          git push || true
